<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {   // falosne produkty
        // \App\Models\Product::factory(100)->create();

        $products = [
        [
            'active' => true,
            'name' => 'Anas Platyrhynchos',
            'description' => 'Extremely realistic duck',
            'quantity' => 50,
            'price' => 49.30,
            'rating' => 4.7,
            'review_count' => 1756,
            'pcs' => 50,
            'material' => 'Vinyl',
            'size' => '10 cm',
            'weight' => '100 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Bubble Duck',
            'description' => 'Classic duck which enjoys bubbles, ready to add a splash of fun to your day',
            'quantity' => 100,
            'price' => 0.30,
            'rating' => 5.0,
            'review_count' => 256,
            'pcs' => 50,
            'material' => 'Rubber',
            'size' => '8 cm',
            'weight' => '80 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Mallard',
            'description' => 'Standing duck figure',
            'quantity' => 40,
            'price' => 7.20,
            'rating' => 5.0,
            'review_count' => 6,
            'pcs' => 50,
            'material' => 'Plastic',
            'size' => '12 cm',
            'weight' => '150 g',
            'age' => '3+',
            'country_of_origin' => 'Czech Republic',
        ],
        [
            'active' => true,
            'name' => 'Chilled Duck',
            'description' => 'Duck enjoying life',
            'quantity' => 25,
            'price' => 48.62,
            'rating' => 5.0,
            'review_count' => 37,
            'pcs' => 50,
            'material' => 'Plastic',
            'size' => '12 cm',
            'weight' => '150 g',
            'age' => '3+',
            'country_of_origin' => 'Czech Republic',
        ],
        [
            'active' => true,
            'name' => 'Coldy',
            'description' => 'Duck which does not like cold',
            'quantity' => 30,
            'price' => 38.60,
            'rating' => 4.5,
            'review_count' => 25,
            'pcs' => 50,
            'material' => 'Vinyl',
            'size' => '10 cm',
            'weight' => '90 g',
            'age' => '6+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Drowning Gluggy',
            'description' => 'Sometimes ducks forget to walk ... or swim',
            'quantity' => 20,
            'price' => 27.30,
            'rating' => 5.0,
            'review_count' => 256,
            'pcs' => 150,
            'material' => 'Silicone',
            'size' => '20 cm',
            'weight' => '300 g',
            'age' => '3+',
            'country_of_origin' => 'Germany',
        ],
        [
            'active' => true,
            'name' => 'Lovey',
            'description' => 'Cute duck bringing love',
            'quantity' => 80,
            'price' => 4.85,
            'rating' => 5.0,
            'review_count' => 1056,
            'pcs' => 150,
            'material' => 'Rubber',
            'size' => '5 cm',
            'weight' => '50 g',
            'age' => '1+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Silhouette Duck',
            'description' => 'Duck',
            'quantity' => 60,
            'price' => 4.85,
            'rating' => 4.2,
            'review_count' => 4,
            'pcs' => 150,
            'material' => 'Plastic',
            'size' => '8 cm',
            'weight' => '70 g',
            'age' => '3+',
            'country_of_origin' => 'Austria',
        ],
        [
            'active' => true,
            'name' => 'Splashy',
            'description' => 'Classic swimming duck which enjoys water',
            'quantity' => 3,
            'price' => 14.85,
            'rating' => 4.2,
            'review_count' => 9,
            'pcs' => 150,
            'material' => 'Plastic',
            'size' => '8 cm',
            'weight' => '32 g',
            'age' => '4+',
            'country_of_origin' => 'Austria',
        ],
        [
            'active' => true,
            'name' => 'Traveller',
            'description' => 'Duck which will swim around the Earth',
            'quantity' => 60,
            'price' => 0.63,
            'rating' => 5,
            'review_count' => 14,
            'pcs' => 150,
            'material' => 'Plastic',
            'size' => '10 cm',
            'weight' => '70 g',
            'age' => '3+',
            'country_of_origin' => 'Germany',
        ],
        [
            'active' => true,
            'name' => 'Wave Rider',
            'description' => 'Swim and swim',
            'quantity' => 2,
            'price' => 4.85,
            'rating' => 4.2,
            'review_count' => 4,
            'pcs' => 150,
            'material' => 'Plastic',
            'size' => '8 cm',
            'weight' => '40 g',
            'age' => '3+',
            'country_of_origin' => 'Austria',
        ],
        [
            'active' => true,
            'name' => 'Summer Chiller',
            'description' => 'Just chillin on the beach',
            'quantity' => 150,
            'price' => 3.99,
            'rating' => 4.4,
            'review_count' => 18,
            'pcs' => 40,
            'material' => 'Vinyl',
            'size' => '10 cm',
            'weight' => '40 g',
            'age' => '3+',
            'country_of_origin' => 'Spain',
        ],
        [
            'active' => true,
            'name' => 'Sir Quackalot',
            'description' => 'Meet Sir Quackalot, the noble guardian and visionary mascot of the Lucky Quacky brand. With his steady gaze and impeccable poise, this distinguished drake brings a touch of aristocratic elegance and calm leadership to any sticker collection.',
            'quantity' => 200,
            'price' => 19.99,
            'rating' => 4.6,
            'review_count' => 34,
            'pcs' => 40,
            'material' => 'Plastic',
            'size' => '10 cm',
            'weight' => '50 g',
            'age' => '12+',
            'country_of_origin' => 'Switzerland',
        ],
        [
            'active' => true,
            'name' => 'Old Classic',
            'description' => 'This iconic rubber duck, proudly named Old Classic, has returned to its roots by stripping away all color to let its timeless form shine through clean black and white lines. It serves as a visual tribute to the golden era of bath-time design, ready to bring a touch of nostalgia and elegance to any modern collection.',
            'quantity' => 200,
            'price' => 39.99,
            'rating' => 4.9,
            'review_count' => 184,
            'pcs' => 10,
            'material' => 'Plastic',
            'size' => '10 cm',
            'weight' => '50 g',
            'age' => '12+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Eaten',
            'description' => 'Meet Eaten, the only duck who’s permanently on a "seafood diet" - he sees food and he eats it! He’s cute, he’s hungry, and he’s definitely not sorry about that bite!',
            'quantity' => 150,
            'price' => 13.49,
            'rating' => 4.9,
            'review_count' => 382,
            'pcs' => 50,
            'material' => 'Vinyl',
            'size' => '10 cm',
            'weight' => '40 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Sea Bundle',
            'description' => 'The ultimate Sea Bundle: because life is just better when you’re "quacking" up under the sun. From deep-sea diving to catching the perfect wave, these guys are proof that you don’t need to be a swan to make a splash!',
            'quantity' => 150,
            'price' => 34.49,
            'rating' => 4.1,
            'review_count' => 208,
            'pcs' => 20,
            'material' => 'Vinyl',
            'size' => '40 cm',
            'weight' => '200 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Rainy Saddie',
            'description' => 'Meet Rainy Saddie: The only duck in history who is actually tired of water. He’s officially reached his "quack-ing" point with this weather.',
            'quantity' => 100,
            'price' => 8.49,
            'rating' => 2.3,
            'review_count' => 25,
            'pcs' => 30,
            'material' => 'Vinyl',
            'size' => '8 cm',
            'weight' => '40 g',
            'age' => '3+',
            'country_of_origin' => 'England',
        ],
        [
            'active' => true,
            'name' => 'Chef Berry',
            'description' => 'Upgrade your kitchen squad with Chef Berry. He doesn’t just cook; he brings a 100% gourmet attitude to your collection.',
            'quantity' => 100,
            'price' => 8.69,
            'rating' => 3.2,
            'review_count' => 49,
            'pcs' => 30,
            'material' => 'Vinyl',
            'size' => '8 cm',
            'weight' => '40 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Chill Guy',
            'description' => 'Need more peace in your life? Chill guy is ready to move in with you. He is quiet, low-maintenance, and guarantees a 100% increase in home chill-vibes.',
            'quantity' => 80,
            'price' => 28.79,
            'rating' => 1.0,
            'review_count' => 2,
            'pcs' => 20,
            'material' => 'Vinyl',
            'size' => '10 cm',
            'weight' => '60 g',
            'age' => '3+',
            'country_of_origin' => 'Switzerland',
        ],
        [
            'active' => true,
            'name' => 'Feather',
            'description' => 'Whether it fell from a wandering traveler or a soaring explorer, this feather represents the freedom of the open sky.',
            'quantity' => 250,
            'price' => 1.25,
            'rating' => 2.6,
            'review_count' => 4,
            'pcs' => 30,
            'material' => 'Vinyl',
            'size' => '6 cm',
            'weight' => '25 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'DJ Quack',
            'description' => 'Tired of the same old songs? Let DJ Quack drop the beat! With his signature green headphones and feathers that feel the rhythm, he’s ready to turn your space into a VIP club. Add to your playlist today!',
            'quantity' => 200,
            'price' => 13.75,
            'rating' => 1.6,
            'review_count' => 77,
            'pcs' => 30,
            'material' => 'Vinyl',
            'size' => '8 cm',
            'weight' => '40 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Ducks on the Shelf',
            'description' => 'Why have one duck when you can have a whole row? Perfect for collectors, organizers, or anyone who just wants a row of silent, yellow roommates watching over their room. Get your ducks in a row—literally!',
            'quantity' => 150,
            'price' => 45.95,
            'rating' => 4.1,
            'review_count' => 94,
            'pcs' => 30,
            'material' => 'Vinyl',
            'size' => '8 cm',
            'weight' => '40 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Pondie',
            'description' => 'Pondie is the CEO of relaxation, reigning over his watery kingdom with style and grace. He comes with his own cattails, rocks, and a permanent state of tranquility. Add Pondie to your cart and bring the ultimate garden vibes into your life!',
            'quantity' => 150,
            'price' => 24.95,
            'rating' => 2.8,
            'review_count' => 80,
            'pcs' => 30,
            'material' => 'Vinyl',
            'size' => '8 cm',
            'weight' => '40 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Dark Knight',
            'description' => 'He is the king of the dark waters. He’s 50% mystery, 50% blush, and 100% too cool for your average breadcrumbs. Grab this noir legend before he disappears into the mist!',
            'quantity' => 150,
            'price' => 42.50,
            'rating' => 3.9,
            'review_count' => 51,
            'pcs' => 30,
            'material' => 'Vinyl',
            'size' => '8 cm',
            'weight' => '40 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Mama & Mini',
            'description' => 'Mother-daughter duo in a gorgeous purple-and-cyan glow. They’re light, they’re trendy, and they’re ready to hitch a ride straight into your heart. Add this vibrant pair to your cart!',
            'quantity' => 150,
            'price' => 29.99,
            'rating' => 4.7,
            'review_count' => 112,
            'pcs' => 20,
            'material' => 'Vinyl',
            'size' => '8 cm',
            'weight' => '40 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Santa Quack',
            'description' => '10% Reindeer energy, 90% holiday magic. The perfect festive addition for anyone who wants to celebrate Christmas ’duck-style’.',
            'quantity' => 150,
            'price' => 11.99,
            'rating' => 4.5,
            'review_count' => 243,
            'pcs' => 30,
            'material' => 'Vinyl',
            'size' => '8 cm',
            'weight' => '40 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Mr. Pipi',
            'description' => 'You just told a joke and Mr. Pipi is waiting for the punchline. This legendary face is ready to judge your snack choices from the comfort of your shelf. Grab the ultimate icon today!',
            'quantity' => 150,
            'price' => 7.00,
            'rating' => 2.5,
            'review_count' => 107,
            'pcs' => 30,
            'material' => 'Vinyl',
            'size' => '8 cm',
            'weight' => '40 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Single Track',
            'description' => 'Just a track left by a duck.',
            'quantity' => 150,
            'price' => 2.50,
            'rating' => 1.2,
            'review_count' => 40,
            'pcs' => 30,
            'material' => 'Vinyl',
            'size' => '5 cm',
            'weight' => '30 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Cloudy Floater',
            'description' => 'Currently out of office. Please leave a crumb after the beep.',
            'quantity' => 150,
            'price' => 34.50,
            'rating' => 3.3,
            'review_count' => 62,
            'pcs' => 30,
            'material' => 'Vinyl',
            'size' => '10 cm',
            'weight' => '50 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'The Quacktastic Trio',
            'description' => '1 Mom, 2 Minis, 100% full-time commitment. The perfect reminder that sometimes, you just have to follow the leader.',
            'quantity' => 150,
            'price' => 5.95,
            'rating' => 5,
            'review_count' => 12,
            'pcs' => 30,
            'material' => 'Vinyl',
            'size' => '10 cm',
            'weight' => '50 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Eggs',
            'description' => 'Pretty little baby.',
            'quantity' => 150,
            'price' => 0.95,
            'rating' => 3.9,
            'review_count' => 167,
            'pcs' => 20,
            'material' => 'Vinyl',
            'size' => '5 cm',
            'weight' => '30 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Businessman',
            'description' => 'Always ready! Whatever you need, whenever you need it.',
            'quantity' => 200,
            'price' => 4.50,
            'rating' => 4.3,
            'review_count' => 62,
            'pcs' => 100,
            'material' => 'Plastic',
            'size' => '5 cm',
            'weight' => '20 g',
            'age' => '4+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Crazy Rider',
            'description' => 'Ready for a little thrill and a lot of fun? Crazy Rider is here for you!',
            'quantity' => 7,
            'price' => 32.40,
            'rating' => 4.7,
            'review_count' => 7,
            'pcs' => 60,
            'material' => 'Plastic',
            'size' => '5 cm',
            'weight' => '20 g',
            'age' => '3+',
            'country_of_origin' => 'Germany',
        ],
        [
            'active' => true,
            'name' => 'Detective',
            'description' => 'A riddle needed to be solved? No problems!',
            'quantity' => 7,
            'price' => 5.40,
            'rating' => 2.7,
            'review_count' => 6,
            'pcs' => 60,
            'material' => 'Plastic',
            'size' => '5 cm',
            'weight' => '20 g',
            'age' => '3+',
            'country_of_origin' => 'Germany',
        ],
        [
            'active' => true,
            'name' => 'Mr. Quacker',
            'description' => 'A simple "quack" is sometimes enough.',
            'quantity' => 23,
            'price' => 5.40,
            'rating' => 2.4,
            'review_count' => 7,
            'pcs' => 60,
            'material' => 'Plastic',
            'size' => '5 cm',
            'weight' => '20 g',
            'age' => '3+',
            'country_of_origin' => 'Germany',
        ],
        [
            'active' => true,
            'name' => 'Smarty',
            'description' => 'Smart and cute? What more could you ask for?',
            'quantity' => 23,
            'price' => 5.40,
            'rating' => 5,
            'review_count' => 139,
            'pcs' => 100,
            'material' => 'Plastic',
            'size' => '5 cm',
            'weight' => '20 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Super-duper Duck',
            'description' => 'Bring a little super-duper fun into your life with this charming duck. Cute, playful, and impossible not to love!',
            'quantity' => 23,
            'price' => 15.40,
            'rating' => 4.7,
            'review_count' => 139,
            'pcs' => 100,
            'material' => 'Plastic',
            'size' => '5 cm',
            'weight' => '20 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Tuby',
            'description' => 'Oh look, more water! This happy little duck can never get enough of it.',
            'quantity' => 23,
            'price' => 15.40,
            'rating' => 3.7,
            'review_count' => 5,
            'pcs' => 100,
            'material' => 'Plastic',
            'size' => '5 cm',
            'weight' => '20 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Duck Chilling',
            'description' => 'Vacation time.',
            'quantity' => 23,
            'price' => 15.00,
            'rating' => 4.0,
            'review_count' => 29,
            'pcs' => 100,
            'material' => 'Plastic',
            'size' => '10 cm',
            'weight' => '50 g',
            'age' => '5+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Springer',
            'description' => 'Spring is coming duck!',
            'quantity' => 42,
            'price' => 12.50,
            'rating' => 4.8,
            'review_count' => 156,
            'pcs' => 30,
            'material' => 'Vinyl',
            'size' => '15 cm',
            'weight' => '120 g',
            'age' => '6+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Normal Duck',
            'description' => 'No batteries, no special effects. Just a honest, yellow duck that does exactly what a duck is supposed to do - exist beautifully.',
            'quantity' => 500,
            'price' => 42.99,
            'rating' => 4.9,
            'review_count' => 5432,
            'pcs' => 30,
            'material' => 'Rubber',
            'size' => '8 cm',
            'weight' => '60 g',
            'age' => '0+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Bobik',
            'description' => 'He knows if you’ve been bad or good, but he’ll probably give you a squeak anyway. With a hand-painted red hat and a beard made of pure holiday spirit, he’s ready to turn your bathtub into a winter wonderland.',
            'quantity' => 120,
            'price' => 14.99,
            'rating' => 2.6,
            'review_count' => 890,
            'pcs' => 2,
            'material' => 'Vinyl',
            'size' => '11 cm',
            'weight' => '75 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Magician',
            'description' => 'Now you see him, now you... well, he is still there, but looking much more mystical! The Great Quackini comes with a tiny velvet-textured top hat and a hidden card behind his wing. Perfect for making your boredom disappear.',
            'quantity' => 45,
            'price' => 0.90,
            'rating' => 3.3,
            'review_count' => 124,
            'pcs' => 2,
            'material' => 'Vinyl',
            'size' => '12 cm',
            'weight' => '85 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Bubble Queen',
            'description' => 'The master of bathtub meditation. This duck doesn’t just float; she glides through a sea of bubbles with royal elegance. If you’re looking for a sign to finally take that long bath and ignore your emails, this is it.',
            'quantity' => 85,
            'price' => 9.40,
            'rating' => 1.8,
            'review_count' => 312,
            'pcs' => 2,
            'material' => 'Soft Rubber',
            'size' => '9 cm',
            'weight' => '70 g',
            'age' => '0+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Frayer',
            'description' => 'The coolest duck in the tub. Period. With backward cap and sunglasses, this monochrome icon brings pure attitude to your collection. He doesn’t need colors to shine; his style speaks for itself.',
            'quantity' => 110,
            'price' => 44.20,
            'rating' => 4.9,
            'review_count' => 420,
            'pcs' => 10,
            'material' => 'Vinyl',
            'size' => '10 cm',
            'weight' => '80 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
    ];

        foreach ($products as $product) {
            Product::create($product);
        }


    }
}
