<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {   // falosne produkty
        // \App\Models\Product::factory(100)->create();

        $products = [
        [
            'active' => true,
            'name' => 'Anas Platyrhynchos',
            'description' => 'Extremely realistic duck',
            'quantity' => 50,
            'price' => 147.30,
            'rating' => 4.7,
            'review_count' => 1756,
            'pcs' => 50,
            'material' => 'Vinyl',
            'size' => '10 cm',
            'weight' => '100 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Bubble Duck',
            'description' => 'Classic duck which enjoys bubbles',
            'quantity' => 100,
            'price' => 0.30,
            'rating' => 5.0,
            'review_count' => 256,
            'pcs' => 50,
            'material' => 'Rubber',
            'size' => '8 cm',
            'weight' => '80 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Mallard',
            'description' => 'Standing duck figure',
            'quantity' => 40,
            'price' => 7.20,
            'rating' => 5.0,
            'review_count' => 6,
            'pcs' => 50,
            'material' => 'Plastic',
            'size' => '12 cm',
            'weight' => '150 g',
            'age' => '3+',
            'country_of_origin' => 'Czech Republic',
        ],
        [
            'active' => true,
            'name' => 'Chilled Duck',
            'description' => 'Duck enjoying life',
            'quantity' => 25,
            'price' => 58.62,
            'rating' => 5.0,
            'review_count' => 37,
            'pcs' => 50,
            'material' => 'Plastic',
            'size' => '12 cm',
            'weight' => '150 g',
            'age' => '3+',
            'country_of_origin' => 'Czech Republic',
        ],
        [
            'active' => true,
            'name' => 'Coldy',
            'description' => 'Duck which does not like cold',
            'quantity' => 30,
            'price' => 58.60,
            'rating' => 4.5,
            'review_count' => 25,
            'pcs' => 50,
            'material' => 'Vinyl',
            'size' => '10 cm',
            'weight' => '90 g',
            'age' => '6+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Drowning Gluggy',
            'description' => 'Sometimes ducks forget to walk or swim',
            'quantity' => 20,
            'price' => 147.30,
            'rating' => 5.0,
            'review_count' => 256,
            'pcs' => 150,
            'material' => 'Silicone',
            'size' => '20 cm',
            'weight' => '300 g',
            'age' => '3+',
            'country_of_origin' => 'Germany',
        ],
        [
            'active' => true,
            'name' => 'Lovey',
            'description' => 'Cute duck bringing love',
            'quantity' => 80,
            'price' => 4.85,
            'rating' => 5.0,
            'review_count' => 1056,
            'pcs' => 150,
            'material' => 'Rubber',
            'size' => '5 cm',
            'weight' => '50 g',
            'age' => '1+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Silhouette Duck',
            'description' => 'Duck',
            'quantity' => 60,
            'price' => 4.85,
            'rating' => 4.2,
            'review_count' => 4,
            'pcs' => 150,
            'material' => 'Plastic',
            'size' => '8 cm',
            'weight' => '70 g',
            'age' => '3+',
            'country_of_origin' => 'Austria',
        ],
        [
            'active' => true,
            'name' => 'Splashy',
            'description' => 'Classic swimming duck which enjoys water',
            'quantity' => 3,
            'price' => 14.85,
            'rating' => 4.2,
            'review_count' => 9,
            'pcs' => 150,
            'material' => 'Plastic',
            'size' => '8 cm',
            'weight' => '32 g',
            'age' => '4+',
            'country_of_origin' => 'Austria',
        ],
        [
            'active' => true,
            'name' => 'Traveller',
            'description' => 'Duck which will swim around the Earth',
            'quantity' => 60,
            'price' => 0.63,
            'rating' => 5,
            'review_count' => 14,
            'pcs' => 150,
            'material' => 'Plastic',
            'size' => '10 cm',
            'weight' => '70 g',
            'age' => '3+',
            'country_of_origin' => 'Germany',
        ],
        [
            'active' => true,
            'name' => 'Wave Rider',
            'description' => 'Swim and swim',
            'quantity' => 2,
            'price' => 4.85,
            'rating' => 4.2,
            'review_count' => 4,
            'pcs' => 150,
            'material' => 'Plastic',
            'size' => '8 cm',
            'weight' => '40 g',
            'age' => '3+',
            'country_of_origin' => 'Austria',
        ],
        [
            'active' => true,
            'name' => 'Summer Chiller',
            'description' => 'Just chillin on the beach',
            'quantity' => 150,
            'price' => 3.99,
            'rating' => 4.4,
            'review_count' => 18,
            'pcs' => 40,
            'material' => 'Vinyl',
            'size' => '10 cm',
            'weight' => '40 g',
            'age' => '3+',
            'country_of_origin' => 'Spain',
        ],
        [
            'active' => true,
            'name' => 'Sir Quackalot',
            'description' => 'Meet Sir Quackalot, the noble guardian and visionary mascot of the Lucky Quacky brand. With his steady gaze and impeccable poise, this distinguished drake brings a touch of aristocratic elegance and calm leadership to any sticker collection.',
            'quantity' => 200,
            'price' => 19.99,
            'rating' => 4.6,
            'review_count' => 34,
            'pcs' => 40,
            'material' => 'Plastic',
            'size' => '10 cm',
            'weight' => '50 g',
            'age' => '12+',
            'country_of_origin' => 'Switzerland',
        ],
        [
            'active' => true,
            'name' => 'Old Classic',
            'description' => 'This iconic rubber duck, proudly named Old Classic, has returned to its roots by stripping away all color to let its timeless form shine through clean black and white lines. It serves as a visual tribute to the golden era of bath-time design, ready to bring a touch of nostalgia and elegance to any modern collection.',
            'quantity' => 200,
            'price' => 39.99,
            'rating' => 4.9,
            'review_count' => 184,
            'pcs' => 10,
            'material' => 'Plastic',
            'size' => '10 cm',
            'weight' => '50 g',
            'age' => '12+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Eaten',
            'description' => 'Meet Eaten, the only duck who’s permanently on a "seafood diet" - he sees food and he eats it! He’s cute, he’s hungry, and he’s definitely not sorry about that bite!',
            'quantity' => 150,
            'price' => 5.49,
            'rating' => 4.9,
            'review_count' => 382,
            'pcs' => 50,
            'material' => 'Vinyl',
            'size' => '10 cm',
            'weight' => '40 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Sea Bundle',
            'description' => 'The ultimate Sea Bundle: because life is just better when you’re "quacking" up under the sun. From deep-sea diving to catching the perfect wave, these guys are proof that you don’t need to be a swan to make a splash!',
            'quantity' => 150,
            'price' => 10.49,
            'rating' => 4.1,
            'review_count' => 208,
            'pcs' => 20,
            'material' => 'Vinyl',
            'size' => '40 cm',
            'weight' => '200 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Rainy Saddie',
            'description' => 'Meet Rainy Saddie: The only duck in history who is actually tired of water. He’s officially reached his "quack-ing" point with this weather.',
            'quantity' => 100,
            'price' => 1.49,
            'rating' => 2.3,
            'review_count' => 25,
            'pcs' => 30,
            'material' => 'Vinyl',
            'size' => '8 cm',
            'weight' => '40 g',
            'age' => '3+',
            'country_of_origin' => 'England',
        ],
        [
            'active' => true,
            'name' => 'Chef Berry',
            'description' => 'Upgrade your kitchen squad with Chef Berry. He doesn’t just cook; he brings a 100% gourmet attitude to your collection.',
            'quantity' => 100,
            'price' => 2.69,
            'rating' => 3.2,
            'review_count' => 49,
            'pcs' => 30,
            'material' => 'Vinyl',
            'size' => '8 cm',
            'weight' => '40 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
        [
            'active' => true,
            'name' => 'Chill Guy',
            'description' => 'Need more peace in your life? Chill guy is ready to move in with you. He is quiet, low-maintenance, and guarantees a 100% increase in home chill-vibes.',
            'quantity' => 80,
            'price' => 28.79,
            'rating' => 1.0,
            'review_count' => 2,
            'pcs' => 20,
            'material' => 'Vinyl',
            'size' => '10 cm',
            'weight' => '60 g',
            'age' => '3+',
            'country_of_origin' => 'Switzerland',
        ],
        [
            'active' => true,
            'name' => 'Feather',
            'description' => 'Whether it fell from a wandering traveler or a soaring explorer, this feather represents the freedom of the open sky.',
            'quantity' => 250,
            'price' => 1.25,
            'rating' => 2.6,
            'review_count' => 4,
            'pcs' => 30,
            'material' => 'Vinyl',
            'size' => '6 cm',
            'weight' => '25 g',
            'age' => '3+',
            'country_of_origin' => 'Slovakia',
        ],
    ];

        foreach ($products as $product) {
            Product::create($product);
        }


    }
}
